---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(ggplot2)
library(tidyverse)
library(tidyr)
library(rstatix)
library(svglite)
```

```{r}
library(readxl)
ph_test <- read_excel("C:/Users/ariju/Desktop/KURSINIS/differrent ph test.xlsx", 
    sheet = "Sheet1", skip = 1)
```

```{r}
ph_test <- ph_test |> 
  select(
    -Content, -`Sample X7`, -`Sample X4`, -`Sample X2`
  )

ph_test <- ph_test |> 
  slice(-c(1:3))
```

```{r}
ph_tested_mean <- ph_test |> 
  rowwise() |> 
    mutate(
    "2" = mean(c(`Sample X5`, `Sample X6`)),
    "4" = mean(c(`Sample X1`, `Sample X3`)),
    "6" = mean(c(`Sample X8`, `Sample X9`)),
    "7.4" = mean(c(`Sample X10`, `Sample X11`, `Sample X12`))
  ) |> 
  ungroup()

ph_tested_sd <- ph_test |> 
  rowwise() |> 
    mutate(
    "2" = sd(c(`Sample X5`, `Sample X6`)),
    "4" = sd(c(`Sample X1`, `Sample X3`)),
    "6" = sd(c(`Sample X8`, `Sample X9`)),
    "7.4" = sd(c(`Sample X10`, `Sample X11`, `Sample X12`))
  ) |> 
  ungroup()
```

```{r}
ph_tested_mean <- select(
  ph_tested_mean,
  Time, "2", "4", "6", "7.4"
  )

ph_tested_sd <- select(
  ph_tested_sd,
  Time, "2", "4", "6", "7.4"
)
```

```{r}
ph_tested_mean <- ph_tested_mean |> 
  pivot_longer(
    cols =  c("2", "4", "6", "7.4"), 
    names_to = "sample", 
    values_to = "data",
    names_transform = list(sample = as.factor)
  )
ph_tested_sd <- ph_tested_sd |> 
  pivot_longer(
    cols =  c("2", "4", "6", "7.4"), 
    names_to = "sample", 
    values_to = "data_sd",
    names_transform = list(sample = as.factor)
  )
```

```{r}
ph_test_different <- ph_test |> 
  pivot_longer(
    cols =  c(`Sample X1`:`Sample X12`), 
    names_to = "sample", 
    values_to = "data",
    names_transform = list(sample = as.factor)
  )
```

```{r}
ph_final <- inner_join(
  ph_tested_mean, ph_tested_sd, by = c("Time", "sample")
  )
```

```{r}
ph_test_different <- ph_test_different %>%
  mutate(sample_number = as.numeric(gsub("Sample X", "", sample)),
         pH = case_when(
           sample_number %in% 1:3 ~ "4",
           sample_number %in% 4:6 ~ "2",
           sample_number %in% 7:9 ~ "6",
           sample_number %in% 10:12 ~ "7.4",
           TRUE ~ "Other"
         ))

ph_test_different <- ph_test_different %>%
  mutate(pH = factor(pH, levels = c("4","2", "6", "7.4")))
```

```{r}
ph_pic <- ph_final |> 
  ggplot(aes(x = Time, y = data, fill = sample)) +
  geom_line(show.legend = FALSE, size = 1, aes(color = sample))+
  geom_ribbon(aes(ymin = data - data_sd, ymax = data + data_sd), alpha = 0.4, color = NA) +
  theme_test() +
  labs(
    title = "ThT fluorescencijos intensyvumo pokytis laike",
    subtitle = "pH lygio poveikis",
    x = "Laikas, h",
    y = "ThT fluorescencijos intensyvumas, a.u.",
    color = "pH level",
    fill = "pH lygis"
  ) +
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.15, 0.8)
    )
```

```{r}
ggsave("ph_pic.svg", plot = ph_pic, device = "svg")
```

```{r}
ph_pic
```
